// app/embed.js/route.ts
//
// The loader script (build spec §14 "Embed system"). What a client pastes —
// generated by lib/engine/embedSnippet.ts, which is the single source of
// truth for exactly which data-* attributes this script understands:
//
//   <div data-playloop="slug" data-placement="modal" data-min-width="320"
//        data-width="480" data-height="640" data-trigger="load"
//        data-trigger-label="Play & win"></div>
//   <script src="https://playloop.app/embed.js" async></script>
//
// This route serves that script as `application/javascript`, cacheable at
// the edge. Per placement:
//   - "section" (default) / "fullpage": mounts a sandboxed iframe pointing
//     at /play/:slug directly into the host element, immediately.
//     data-min-width (from the template's own capability JSON, at snippet-
//     generation time) floors the host box so a too-narrow container can't
//     silently squish the game; data-width (a merchant's own choice — see
//     embed/page.tsx's Size section) additionally CAPS it. "fullpage" floors
//     the host's height at the visitor's own viewport height instead, so it
//     reads as a real full-page moment rather than just a taller section —
//     data-height is ignored there for the same reason.
//   - "modal": renders a trigger BUTTON in place of the host element (or
//     attaches to the merchant's own element via data-trigger-selector) and
//     builds the overlay + iframe lazily on first open — never while
//     hidden, since a container created with display:none has no box for
//     the runtime to measure (lib/runtime/stage.ts sizes off
//     getBoundingClientRect() and a later display:none -> block toggle
//     isn't guaranteed to fire a ResizeObserver callback). data-trigger
//     controls WHEN it first opens: "click" (default) only on a visitor's
//     click; "load" also opens it once automatically shortly after the page
//     loads (the button still renders, so a visitor who closes it can
//     reopen it). Reopens reuse the same iframe rather than rebuilding it.
//   - data-width/data-height (present for section/modal, not fullpage) are
//     forwarded to /play/:slug as ?width=/?height=, which lib/runtime/
//     stage.ts treats as a cap/target layered on top of — never smaller
//     than — the template's own placement minimums.
//   - the postMessage auto-height handshake (an iframe never grows to fit
//     its content on its own — build spec §23) is shared by both paths.
//   - passes the host's accent colour / font through as query params, if
//     the host element declares them via data-accent / data-font.
//   - degrades silently on any failure — collapses to nothing, never a
//     broken frame, never a console error on someone else's page. Hosting
//     is a promise: if PlayLoop goes down, nothing should break on a page
//     a client owns.
//
// No browser storage anywhere in this file either (build spec §4/§14/§23).

// Runs at the edge for low-latency, CDN-friendly delivery — this route has
// no sharp/Node dependency, unlike the pipeline's engine routes.
export const runtime = "edge";

function buildLoaderScript(fallbackOrigin: string): string {
  // Kept as one self-invoking function, defensively wrapped so a failure
  // anywhere inside never throws on the host page (build spec §14: "never
  // a broken frame, never a console error on someone else's site").
  return `(function () {
  try {
    if (window.__playloopEmbedLoaded) return;
    window.__playloopEmbedLoaded = true;

    var FALLBACK_ORIGIN = ${JSON.stringify(fallbackOrigin)};
    var MAX_IFRAME_HEIGHT = 4000;
    var DEFAULT_TRIGGER_LABEL = 'Play & win';

    function resolveOrigin() {
      try {
        var cs = document.currentScript;
        if (cs && cs.src) return new URL(cs.src).origin;
      } catch (e) {}
      return FALLBACK_ORIGIN;
    }
    var BASE = resolveOrigin();

    function numAttr(host, name) {
      var raw = host.getAttribute(name);
      var n = raw ? parseFloat(raw) : NaN;
      return isFinite(n) && n > 0 ? n : null;
    }

    function paramsFor(host) {
      var params = new URLSearchParams();
      var accent = host.getAttribute('data-accent');
      var font = host.getAttribute('data-font');
      var placement = host.getAttribute('data-placement');
      var width = numAttr(host, 'data-width');
      var height = numAttr(host, 'data-height');
      if (accent) params.set('accent', accent);
      if (font) params.set('font', font);
      if (placement) params.set('placement', placement);
      if (width) params.set('width', String(Math.round(width)));
      // "fullpage" defines its own height from the visitor's real viewport
      // (below) — a merchant's data-height would fight that, so it's simply
      // not forwarded for that one placement.
      if (height && placement !== 'fullpage') params.set('height', String(Math.round(height)));
      return params;
    }

    function buildIframe(slug, params) {
      var iframe = document.createElement('iframe');
      var qs = params.toString();
      iframe.src = BASE + '/play/' + encodeURIComponent(slug) + (qs ? '?' + qs : '');
      iframe.setAttribute('sandbox', 'allow-scripts allow-same-origin allow-popups');
      iframe.setAttribute('scrolling', 'no');
      iframe.setAttribute('frameborder', '0');
      iframe.title = 'Playable game';
      iframe.style.display = 'block';
      iframe.style.width = '100%';
      iframe.style.maxWidth = '100%';
      iframe.style.border = '0';
      iframe.style.overflow = 'hidden';
      // Zero height until the play page's first postMessage resize —
      // never a fixed height clipping on mobile or leaving dead space.
      iframe.style.height = '0px';
      return iframe;
    }

    // maxHeight caps how tall the resize handshake is allowed to grow the
    // iframe — used by the modal path so a long game can't grow the overlay
    // past the visitor's own screen (the modal card scrolls internally
    // instead once content exceeds it).
    function watchResize(iframe, maxHeight) {
      var cap = maxHeight ? Math.min(MAX_IFRAME_HEIGHT, maxHeight) : MAX_IFRAME_HEIGHT;
      function onMessage(event) {
        try {
          if (!event || !event.data || event.data.type !== 'playloop:resize') return;
          if (event.source !== iframe.contentWindow) return;
          var height = Number(event.data.height);
          if (!isFinite(height) || height <= 0) return;
          iframe.style.height = Math.min(Math.ceil(height), cap) + 'px';
        } catch (e) {
          // Never throw from a message handler running on the host page.
        }
      }
      window.addEventListener('message', onMessage);
    }

    function mountInline(host, placement) {
      var minWidth = numAttr(host, 'data-min-width');
      if (minWidth) host.style.minWidth = minWidth + 'px';
      // A merchant's own chosen width (embed/page.tsx's Size section) caps
      // the host box; it can never win against the template's own floor
      // above, so a width smaller than the game can function in is ignored
      // rather than producing a broken layout.
      var width = numAttr(host, 'data-width');
      if (width) host.style.maxWidth = Math.max(width, minWidth || 0) + 'px';

      var params = paramsFor(host);
      var iframe = buildIframe(host.getAttribute('data-playloop'), params);

      if (placement === 'fullpage') {
        // A real full-page moment, not just a taller section. CSS vh units
        // computed INSIDE the iframe would be relative to the iframe's own
        // (initially zero) box, not the visitor's actual screen — a circular
        // problem an iframe boundary can't resolve on its own. Instead the
        // PARENT page (the only place that actually knows the real viewport
        // size) measures it and hands the pixel value across as a query
        // param; /play/:slug uses that exact number for its own min-height,
        // and floors the iframe at the same value immediately so there's no
        // flash of a short frame before the first postMessage resize lands.
        var vh = window.innerHeight || 0;
        if (vh > 0) {
          params.set('viewportHeight', String(Math.round(vh)));
          iframe.src = BASE + '/play/' + encodeURIComponent(host.getAttribute('data-playloop')) + '?' + params.toString();
          iframe.style.height = Math.round(vh) + 'px';
          host.style.minHeight = vh + 'px';
        }
      }

      watchResize(iframe, null);
      host.appendChild(iframe);
    }

    // --- modal: trigger button + lazily-built overlay ----------------------

    var modalStylesInjected = false;
    function ensureModalStyles() {
      if (modalStylesInjected) return;
      modalStylesInjected = true;
      var style = document.createElement('style');
      style.textContent =
        '.playloop-trigger{display:inline-flex;align-items:center;justify-content:center;' +
        'padding:12px 26px;border-radius:999px;border:0;font:600 15px/1.2 -apple-system,' +
        'BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;cursor:pointer;background:#4F46E5;' +
        'color:#fff;box-shadow:0 4px 14px rgba(0,0,0,.18);transition:filter .15s ease,' +
        'transform .1s ease}' +
        '.playloop-trigger:hover{filter:brightness(1.08)}' +
        '.playloop-trigger:active{transform:scale(.97)}' +
        '.playloop-overlay{position:fixed;inset:0;z-index:2147483000;display:none;' +
        'align-items:center;justify-content:center;padding:20px;background:rgba(15,15,20,.62);' +
        'opacity:0;transition:opacity .18s ease}' +
        '.playloop-overlay.playloop-open{opacity:1}' +
        '.playloop-modal-card{position:relative;width:100%;max-width:460px;max-height:92vh;' +
        'overflow:auto;border-radius:20px;background:#fff;box-shadow:0 24px 60px rgba(0,0,0,.35);' +
        'transform:scale(.96);transition:transform .18s ease}' +
        '.playloop-overlay.playloop-open .playloop-modal-card{transform:scale(1)}' +
        '.playloop-modal-close{position:absolute;top:8px;right:8px;z-index:1;width:32px;' +
        'height:32px;border-radius:999px;border:0;background:rgba(0,0,0,.55);color:#fff;' +
        'font-size:18px;line-height:1;cursor:pointer}';
      document.head.appendChild(style);
    }

    function mountModal(host) {
      ensureModalStyles();
      var slug = host.getAttribute('data-playloop');
      var label = host.getAttribute('data-trigger-label') || DEFAULT_TRIGGER_LABEL;
      var minWidth = numAttr(host, 'data-min-width');
      var width = numAttr(host, 'data-width');
      var triggerSelector = host.getAttribute('data-trigger-selector');
      var openOnLoad = host.getAttribute('data-trigger') === 'load';

      var overlay = null; // built on first open only — never while hidden
      var onKeydown = function (e) {
        if (e.key === 'Escape') close();
      };

      function open() {
        if (!overlay) {
          overlay = document.createElement('div');
          overlay.className = 'playloop-overlay';
          overlay.setAttribute('role', 'dialog');
          overlay.setAttribute('aria-modal', 'true');
          overlay.addEventListener('click', function (e) {
            if (e.target === overlay) close();
          });

          var card = document.createElement('div');
          card.className = 'playloop-modal-card';
          // An explicit merchant width wins outright; otherwise fall back to
          // the default 460px cap from the stylesheet, widened only if the
          // template's own floor needs more room than that (e.g. a wider
          // slider-based game) — never narrower than that floor either way.
          if (width) {
            card.style.maxWidth = Math.max(width, minWidth || 0) + 'px';
          } else if (minWidth) {
            card.style.maxWidth = Math.max(460, minWidth) + 'px';
          }

          var closeBtn = document.createElement('button');
          closeBtn.type = 'button';
          closeBtn.className = 'playloop-modal-close';
          closeBtn.setAttribute('aria-label', 'Close');
          closeBtn.textContent = '\\u00D7';
          closeBtn.addEventListener('click', close);

          var iframe = buildIframe(slug, paramsFor(host));
          watchResize(iframe, window.innerHeight * 0.85);

          card.appendChild(closeBtn);
          card.appendChild(iframe);
          overlay.appendChild(card);
          document.body.appendChild(overlay);
        }
        overlay.style.display = 'flex';
        // Next frame, so the transition plays instead of the overlay just
        // appearing at full opacity (display:none -> flex must land first).
        window.requestAnimationFrame(function () {
          overlay.className = 'playloop-overlay playloop-open';
        });
        document.body.style.overflow = 'hidden';
        document.addEventListener('keydown', onKeydown);
      }

      function close() {
        if (!overlay) return;
        overlay.className = 'playloop-overlay';
        document.body.style.overflow = '';
        document.removeEventListener('keydown', onKeydown);
        window.setTimeout(function () {
          if (overlay) overlay.style.display = 'none';
        }, 180);
      }

      if (triggerSelector) {
        var custom = document.querySelector(triggerSelector);
        if (custom) {
          custom.addEventListener('click', function (e) {
            e.preventDefault();
            open();
          });
        }
        // host stays empty — the merchant's own element is the trigger —
        // but data-trigger="load" still applies below regardless of which
        // element opens it on click.
      } else {
        var button = document.createElement('button');
        button.type = 'button';
        button.className = 'playloop-trigger';
        button.textContent = label;
        button.addEventListener('click', open);
        host.appendChild(button);
      }

      if (openOnLoad) {
        // A short, deliberate delay rather than instant: an overlay that
        // appears before a visitor has seen anything else on the page reads
        // as a pop-up ad, not an invitation. The trigger (button or the
        // merchant's own element) still opens it again after this fires, so
        // closing it once doesn't lose the ability to open it later.
        window.setTimeout(open, 600);
      }
    }

    function mountOne(host) {
      try {
        if (!host || host.nodeType !== 1) return;
        if (host.getAttribute('data-playloop-mounted') === '1') return;
        var slug = host.getAttribute('data-playloop');
        if (!slug) return;
        host.setAttribute('data-playloop-mounted', '1');

        var placement = host.getAttribute('data-placement') || 'section';
        if (placement === 'modal') {
          mountModal(host);
        } else {
          mountInline(host, placement);
        }
      } catch (e) {
        // Collapse silently — this one embed just never appears.
      }
    }

    function mountAll() {
      try {
        var hosts = document.querySelectorAll('[data-playloop]');
        for (var i = 0; i < hosts.length; i++) mountOne(hosts[i]);
      } catch (e) {}
    }

    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', mountAll);
    } else {
      mountAll();
    }

    // Self-healing rescan, not a one-shot mount: a host page built with
    // React (or another framework that hydrates server-rendered markup)
    // treats the host div as ITS OWN node — when hydration reconciles that
    // node against what it expected to render (zero children) and finds the
    // iframe/button this script just appended, several frameworks (React
    // included) resolve the mismatch by discarding and regenerating the
    // whole node from scratch, which silently deletes everything this
    // script added, marker attribute included. That's a one-time event, not
    // an ongoing fight — so rather than guess at a delay that outlasts
    // hydration (fragile: hydration timing varies with page weight and
    // isn't this script's to know), a MutationObserver on the whole
    // document notices the node getting replaced and simply mounts again;
    // the "data-playloop-mounted" guard in mountOne makes every extra call
    // a no-op everywhere hydration was never a factor. This also means a
    // host div inserted later by client-side routing (an SPA storefront
    // navigating without a full reload) gets picked up too, which a single
    // DOMContentLoaded-time pass never could. Confirmed live: without this,
    // this app's own demo-storefront page (a React server component) had
    // its embed wiped out by hydration on every load.
    if (typeof MutationObserver !== 'undefined' && document.body) {
      var rescanScheduled = false;
      function scheduleRescan() {
        if (rescanScheduled) return;
        rescanScheduled = true;
        setTimeout(function () {
          rescanScheduled = false;
          mountAll();
        }, 0);
      }
      var observer = new MutationObserver(scheduleRescan);
      observer.observe(document.body, { childList: true, subtree: true });
    }
  } catch (e) {
    // Whatever happens, this script must never throw on the host page.
  }
})();
`;
}

export async function GET(request: Request) {
  const envOrigin = process.env.NEXT_PUBLIC_APP_URL?.trim().replace(/\/+$/, "");
  const fallbackOrigin = envOrigin || new URL(request.url).origin;

  const script = buildLoaderScript(fallbackOrigin);

  return new Response(script, {
    status: 200,
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      "Cache-Control": "public, max-age=300",
    },
  });
}
